turtlecoin/turtlecoin-docs

How-To-Mine-TurtleCoin-on-Windows.md
https://faucet.trtl.me/ will only pay out 3 times per day, and from my small simple set, I have gotten from 1 to 3 TRTL per day, not 10...?
=> Changing Item 8 re: faucet

getting_started/Getting-Started.md
* Add Windows installation and blockchain syncing information. 
* Combine Mac and Linux directions.
* Fix a couple formatting issues and a spelling mistake.
=> Updates and formatting

README.md, about/Background-and-History.md, faq/Frequently-Asked-Questions.md, getting_started/Getting-Started-w--TurtleCoin-on-Windows.md
* Fixed typos in README.md (the change in about is hard to see, just added 'as the' in front of 'single source of the truth')
* Added background and history from turtlecoin.lol
* Fixed formatting in the FAQ by adding a little detail to the empty A: lines.
* Added information about bootstrapping the block chain to the Windows Getting Started, and also a couple typos.
=> Typos and Content

guides/Using-Simplewallet-with-Remote-Nodes.md
Changelog:
- Updated to include Turtlenode.io as a remote node
- Updated to include the website address for each remote node service
- Updated formatting in a few places to help with display
- Updated verbiage in a few places.
=> Update to Remote Nodes Page

guides/Using-Simplewallet-with-Remote-Nodes.md
Fixed a typo, formatting error and added steps on how to make .bat file
=> Update Remote Nodes guide to fix errors and make it easier to follow

guides/Participating-in-Raindance.md
changed all variants of RainDance to raindance. Fixed the wording of some sentences here and there
=> Changed wording on raindance guide

guides/Bootstrapping-the-Blockchain.md
Also added an extra line in between each step
=> Changed walletd to simplewallet

guides/mining/Mining.md
Fixed a few typos, mentioned location for payment and statistics may vary a fixed a few grammar issues
=> fixed typos

guides/mining/Mining.md
Pool was shut down, removed it from list of pools
=> removed trtlpool.ninja

guides/mining/Cloud-Mining.md
Updated list of pools and a few minor changes
=> Updated pools

guides/mining/Cloud-Mining.md
=> Add https://trtl.semipool.com

guides/mining/Mining-with-SBC.md
Changed links with markdown so that words are hyperlinked, rather than the full url being written. Also added/removed pools-
Added pools from line 68-78 and removed trtlpool.ninja as it was shutdown.
=> Changed links and added pools

guides/mining/Mining.md
=> Add semipool

guides/Using-trtlbot-plus-plus.md
adding a message on another line after the command in 1 message will work
=> fixed wrong info

guides/Bootstrapping-the-Blockchain.md
=> Formatting

guides/Using-trtlbot-plus-plus.md
=> Updated info

guides/Bootstrapping-the-Blockchain.md
Updated link with what seems to be the direct download link for the latest snapshot
=> Updated link

faq/Frequently-Asked-Questions.md
also fixed fact about mac guide
=> removed donation address

guides/mining/Mining.md
please leave the "guide sponsored by monerise" line, I made the guide and was paid for it, and was given permission to post freely. I was asked to include that line.
If you don't like it you can not use merge this pr and make your own guide
=> Added linux guide for xmr-stak

Home.md, getting_started/new_wallet.md
updated link for new wallets and info
=> updated wallets link

guides/Using-Simplewallet-with-Remote-Nodes.md
=> Change remote node example address

Frequently-Asked-Questions.md
=> add corrupted blockchain in faq

guides/RainBorg-Wat-Dat.md
=> change rainborg image syntax

guides/wallets/Using-Simplewallet.md, guides/wallets/Using-remote-nodes.md
=> split off remote nodes guide

_Sidebar.md
=> add 2 guides to sidebar

guides/mining/Mining-with-SBC.md
also change it to ``` syntax
#explicitisbetterthanimplicit
=> add unzip to reqs

guides/mining/Mining-with-SBC.md
=> add intructions to sbc

developer/Resources.md
See https://www.npmjs.com/package/turtlecoin-rpc
=> Adding NPM package for NodeJS

api/wallet-rpc-api.md
Added all the python rpc functions @ar-x @timmcleod 
Two issues need to be addressed at https://github.com/arthurk/turtlecoin-python/issues
@arthurk please review the changes
=> Python walletd rpc docs

api/daemon-json-rpc-api.md, api/sidebar.yml, api/wallet-rpc-api.md
@timmcleod @ar-x I have implemented the methods given in original Bytecoin Wiki https://wiki.bytecoin.org/wiki/Daemon_JSON_RPC_API with shell examples and outputs
TurtleCoin also supports some extra methods which have already been implemented in [JS](https://github.com/turtlecoin/turtlecoin-rpc-js) and in [Python](https://github.com/turtlecoin/turtlecoin-rpc-python/pull/6)
If needed.. I am ready to implement those also..
=> Daemon JSON RPC methods and shell examples

api/rpc-api-error-conditions.md, api/sidebar.yml
=> Add error conditions to Walletd RPC documentation

guides/Forking-TurtleCoin.md
This probably needs a good proofread and a spell check :stuck_out_tongue: 
I might have missed sections or gone a bit overboard on others. Let me know what you think.
=> Create a forking guide

Frequently-Asked-Questions.md
=> add a trtl mining calc

api/rpc-api-error-conditions.md
add - where it's empty, fix some formatting and edit/remove the wallet not found error condition for walletd
=> fill in the api docs and make some changes

Contributors.md
=> change contributor username

_Sidebar.md
=> change sidebar link

api/daemon-http-rpc-api.md, api/daemon-json-rpc-api.md, api/sidebar.yml, developer/Resources.md
@ar-x Added HTTP methods separately since many more methods to come into this later
=> Added Daemon HTTP RPC docs in shell and python

api/wallet-rpc-api.md
See further https://github.com/turtlecoin/turtlecoin/pull/453
=> feeinfo -> getFeeInfo

guides/mining/mobile-mining/Using-Tony-Monero.md
Play Store link was dead, now linking to official page
=> Updating Tony Monero link

guides/wallets/Using-remote-nodes.md
=> Hungarian node added

guides/mining/CPU SOLO Mining
A short solo mining guide for Cpu mining in Windows 10
=> Create CPU SOLO Mining

Frequently-Asked-Questions.md, api/daemon-http-rpc-api.md, api/daemon-json-rpc-api.md, api/wallet-rpc-api.md
All of the mixins needed to be deleted or changed to 3
Updated Javascript links to point to the npm repo
Fixed javascript code not displaying correctly
Updated the HTTP-RPC API portion of the wiki to include Javascript
Examples simplified to just the function call without instantiation.
=> Updating Javascript portion of the docs

Frequently-Asked-Questions.md, developer/Resources.md, guides/wallets/Making-a-GUI-Wallet.md, guides/wallets/Making-a-Wallet.md
RPC API links updated in developer resources
Removed Bootstrapping (RIP) in favor of Checkpoints
Updated mixin information
Removed Xamarin Wallet and added Shellnet, T-Scripta, Electron
=> Updated links and wallet info

api/daemon-http-rpc-api.md, api/daemon-json-rpc-api.md, api/wallet-rpc-api.md
Reverts turtlecoin/turtlecoin-docs#220 will this fix it
=> Revert "lets see if it fixes golang examples issue"

guides/wallets/Using-remote-nodes.md
=> Updating node list

guides/Forking-TurtleCoin.md
Hoping all the wiki's will be updated with this patch
=> link newer guide

api/daemon-http-rpc-api.md
fixed typo for --enable-blockexplorer
=> fixed spelling

api/wallet-rpc-api.md
https://github.com/turtlecoin/turtlecoin/blob/development/src/WalletService/PaymentServiceJsonRpcMessages.h#L120
=> Fix incorrect key parameter name

guides/mining/XMR-Stak-Linux-Guide.md
Oef, big update!  Removed dead links, updated stale GPU drivers instructions (linked to original docs now), updated algo and descriptive text, trimmed some fat.
=> Update and edits

_Sidebar.md
=> remove cloud mining from sidebar

README.md
=> change links on readme

guides/mining/mobile-mining/Mining-with-Phone.md, guides/mining/mobile-mining/Using-Termux.md
Wrote up a guide to mine on android devices using Termux.
=> Adding Termux mining Guide

docs/guides/mining/XMR-Stak-Guide.md
added tweaks and tip for xmr stak.
=> Add tuning information for XMR-Stak

docs/Frequently-Asked-Questions.md
Reverts turtlecoin/turtlecoin-docs#288
=> Revert "Remove info linking to exchanges"

docs/guides/mining/Using-Termux.md
=> why not official NinjaRig repo??

docs/guides/mining/violetminer-Guide.md
New config field in violetminer v0.1.1
=> Document SSL config key in violetminer

docs/developer/api/Daemon-HTTP-RPC-API.md
=> Add some missing API function descriptions

docs/guides/mining/Mining.md
There were 2 sentences without periods at the end.
=> I added 2 missing periods after sentences.

docs/guides/wallets/Using-Proton-Wallet.md
i added "the" in front of "future"
=> added leading "the"

website/siteConfig.js, website/static/css/custom.css, website/static/img/turtlecoin_logo.svg
- Changed logo to SVG version
- Fixed header space for mobile
=> Design improvement

website/static/css/custom.css
=> Bigger font-size for the TOC menu on mobile

docs/Frequently-Asked-Questions.md, docs/guides/Using-tipbot.md, docs/guides/wallets/Making-a-Paper-Wallet.md, website/core/Footer.js, website/sidebars.json
- Update trtlbot++ to TIPBOT
- Remove 'Security of trtlbot++'s tipjar (wallet)' section.
Close #325
=> Update trtlbot++ to TIPBOT

docs/guides/mining/Optimizing-RPi-TurtleCoin-Mining.md
=> Update link to Ubuntu Server

docs/guides/wallets/Restoring-Your-Wallet-From-A-Specific-Block-Height-fr.md
Submitted for NeoMin
https://github.com/ReekoD/TurtleCoinWalletRestore/blob/V0.1/restauration.md
=> french translation from ReekoD

docs/guides/wallets/Using-Shellnet.md
dsanon has said on his discord today that Shellnet.pw is shutting down, let's show this in the guide so people don't waste time.
=> Shellnet is shutting down
